---

- name: Install epel-release, Erlang and other tools
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - automake
  - libtool
  - inotify-tools
  - epel-release
  - http://packages.erlang-solutions.com/site/esl/esl-erlang/FLAVOUR_1_general/esl-erlang_21.0.5-1~centos~7_amd64.rpm

- name: Download Elixir repo
  git:
    repo: git://github.com/elixir-lang/elixir.git
    dest: /tmp/elixir
    version: v1.7.1
    accept_hostkey: yes
    force: yes
  register: elixir

- name: Compile Elixir
  shell:
    make clean install chdir=/tmp/elixir
  when: elixir.changed

- name: Add symlinks
  file:
    src: '/usr/local/bin/{{ item.name }}'
    dest: '/usr/bin/{{ item.name }}'
    state: link
  with_items:
  - { name: 'mix' }
  - { name: 'iex' }
  - { name: 'elixir' }
  - { name: 'elixirc' }
  when: elixir.changed

- name: Add PostgreSQL Yum Repository
  yum: name=https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-7-x86_64/pgdg-centos10-10-2.noarch.rpm
  state: present

- name: Install PostgreSQL
  yum: name={{ item }} state=installed
  with_items:
  - postgresql10
  - postgresql10-contrib
  - postgresql10-server
  - postgresql10-libs

- name: Install PostgreSQL Python libraries
  package:
    name: python-psycopg2
    state: present

- name: Initialize a database
  shell: /usr/pgsql-10/bin/postgresql-10-setup initdb

- name: Enable password authentication
  replace:
    path: /var/lib/pgsql/10/data/pg_hba.conf
    regexp: 'ident'
    replace: "md5"

- name: Start and enable PostgreSQL server
  service: name=postgresql-10 state=started enabled=yes