---

- name: Add ubuntu/erlang_solutions signing key
  apt_key:
    url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
    state: present

- name: Add erlang-solutions repository into sources list
  apt_repository:
    repo: deb https://packages.erlang-solutions.com/ubuntu xenial contrib
    state: present

- name: Install erlang and elixir
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
  - esl-erlang
  - elixir

- name: Add PostgreSQL signing key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Add PostgreSQL into sources list
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main
    state: present

- name: Install PostgreSQL and other tools
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
  - postgresql
  - postgresql-contrib
  - automake
  - libtool
  - libpng-dev
  - zlib1g-dev
  - inotify-tools