---
- name: Install Pip (CentOS)
  package:
    name: "python-pip"
    state: present

- name: Ensure OpenSSL dependencies are installed (CentOS)
  package:
     name: "{{ item }}"
     state: present
  with_items: 
    - gcc
    - libffi-devel
    - openssl-devel
    - python-devel    
