---
- name: Install nginx
  apt: name=nginx state=latest
  tags: nginx

- file: path=/etc/nginx/ssl state=directory mode=0755
  tags: nginx

- name: Generate self-signed SSL certificate
  shell: openssl req -new -x509 -nodes -subj "/CN={{ ansible_host }}" -keyout /etc/nginx/ssl/server.key -out /etc/nginx/ssl/server.crt
  notify:
   - reload nginx
  tags: nginx

- name: Install nginx.conf
  template: src={{ item }}.j2 dest=/etc/nginx/ssl/{{ item }} owner=root group=root mode=0644
  with_items:
   - dhparam.pem
  notify:
   - reload nginx

- name: Install nginx conf.d files
  template: src={{ item }}.j2 dest=/etc/nginx/conf.d/{{ item }} owner=root group=root mode=0644
  with_items:
   - default.conf
  notify:
   - reload nginx
  tags: nginx

- name: Ensure nginx is running and enabled to start at boot
  service: name=nginx state=started enabled=yes
  tags: nginx
