---
- name: Install Pip
  apt:
    name: "python3-pip"
    state: present

- name: Ensure OpenSSL dependencies are installed (Ubuntu)
  package:
     name: "{{ item }}"
     state: present
  with_items: 
    - build-essential
    - libssl-dev
    - libffi-dev
    - python-dev


