---

- name: Clone poanetwork/blockscout repo from GitHub
  git:
    repo: "https://github.com/{{ MAIN_REPO_FETCH }}/blockscout"
    dest: "{{ home }}/blockscout"
    version: "{{ blockscout_version }}"

- name: Add explorer dev.secret
  template:
    src: dev.secret.j2
    dest: "{{ home }}/blockscout/apps/explorer/config/dev.secret.exs"

- name: Add block_scout_web dev.secret
  copy:
    src: '{{ home }}/blockscout/apps/block_scout_web/config/dev.secret.exs.example'
    remote_src: yes
    dest: '{{ home }}/blockscout/apps/block_scout_web/config/dev.secret.exs'
    owner: '{{ username }}'
    group: '{{ username }}'
    mode: 0644

- name: Install dependencies
  shell: cd {{ home }}/blockscout && mix local.hex --force && mix do deps.get, local.rebar --force, deps.compile, compile

- name: Change postgres password
  shell: sudo -u postgres psql -c "alter user postgres with encrypted password '{{ postgres_password }}';"

- name: Create user
  become_user: postgres
  postgresql_user:
    name: '{{ db_user }}'
    password: '{{ db_user_password }}'
    role_attr_flags: CREATEDB,SUPERUSER

- name: Create db
  shell: cd {{ home }}/blockscout && mix do ecto.create, ecto.migrate

- name: Install node dependensies in the apps/block_scout_web
  shell: cd {{ home }}/blockscout/apps/block_scout_web/assets && npm install; cd -

- name: Install node-sass
  shell: cd {{ home }}/blockscout/apps/block_scout_web/assets && npm install node-sass --unsafe-perm; cd -

- name: Install node dependensies in the apps/explorer
  npm:
    path: "{{ home }}/blockscout/apps/explorer"
    state: present
  become: true

- name: Install poa-blockscout service
  template: src=poa-blockscout.j2 dest=/etc/systemd/system/poa-blockscout.service owner={{ username }} group={{ username }} mode=0755
  notify:
  - restart poa-blockscout

- name: Ensure poa-blockscout is running and enabled to start at boot
  service: name=poa-blockscout state=started enabled=yes
