---
- name: Create a sandbox instance
  hosts: localhost
  gather_facts: False
  vars:
    key_name: username
    instance_type: t2.large
    security_group: ['default-security']
    image: ami-9d04e4e5
    region: us-west-2
    count: 1
    volumes:
      - device_name: /dev/sda1
        volume_size: 128
        delete_on_termination: true
  tasks:
    - name: Launch instance
      ec2:
        ec2_access_key: "{{ access_key }}"
        ec2_secret_key: "{{ secret_key }}"
        key_name: "{{ key_name }}"
        instance_tags: 
          Name: bootnode
        group: "{{ security_group }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        count: "{{ count }}"
        wait: yes
        region: "{{ region }}"
#        vpc_subnet_id: subnet-XXXXXXXX
        volumes: "{{ volumes }}"
        assign_public_ip: yes
      register:   ec2
    - name: Add new instance to host group
      add_host: hostname={{ item.public_ip }} groupname=launched
      with_items: "{{ ec2.instances }}"
    - name: Wait for SSH to come up
      wait_for: host={{ item.public_dns_name }} port=22 delay=90 timeout=320 state=started
      with_items: "{{ ec2.instances }}"

- name: Installing python
  hosts: launched
  user: ununtu
  sudo: True
  vars:
     ansible_ssh_port: 22
  raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python-minimal)

- name: Configure instance(s)
  hosts: launched
  gather_facts: False
  user: ununtu
  sudo: True
  vars:
     ansible_ssh_port: 22
  gather_facts: True
  roles:
    - preconf
  tags: preconf
  tasks:
    - name: restart machine after setup
      shell: shutdown -r 1
