---
- hosts: all
  user: ubuntu
  become: True
#  user: root
  roles:
    - preconf
  tags: preconf

- hosts: bootnode
  vars:
    PROXY_PORT: "8545"
    username: "bootnode"
    users:
      - name: "bootnode"
    home: "/home/bootnode"
#    logsprefix: "/home/{{ username }}/logs"
#    logentries_user_key: "0665901a-e843-41c5-82c1-2cc4b39f0b21"
  roles:
    - usermanager
#    - logentries
    - nodejs
    - bootnode
    - oracles-logrotate
    - oracles-parity
    - oracles-pm2
    - oracles-netstats
    - nginx
  tags:
    - bootnode

- hosts: mining
  vars:
    username: "mining"
    users:
      - name: "mining"
    home: "/home/mining"
  roles:
    - usermanager
    - nodejs
    - oracles-logrotate
    - oracles-parity
    - oracles-pm2
    - oracles-netstats
    - mining
  tags:
    - mining

- hosts: netstat
  vars:
    PROXY_PORT: "3000"
    NETSTATS_SERVER: "http://localhost:3000"
    username: "netstat"
    users:
      - name: "netstat"
    home: "/home/netstat"
  roles:
    - usermanager
    - nodejs
    - oracles-logrotate
    - netstat
    - nginx
  tags:
    - netstat

- hosts: explorer
  vars:
    PROXY_PORT: "4000"
    explorerS_SERVER: "localhost"
    username: "explorer"
    users:
      - name: "explorer"
    home: "/home/explorer"
  roles:
    - usermanager
    - nodejs
    - oracles-logrotate
    - oracles-parity
    - oracles-pm2
    - explorer
    - nginx
  tags:
    - explorer

- hosts: owner
  vars:
    username: "owner"
    users:
      - name: "owner"
    home: "/home/owner"
  roles:
    - usermanager
    - nodejs
    - oracles-logrotate
    - oracles-parity
    - oracles-pm2
    - oracles-netstats
    - owner
  tags:
    - owner
