---
- hosts: all
  user: ubuntu
  become: True
#  user: root
  roles:
    - preconf
  tags: preconf

- import_playbook: bootnode.yml
- import_playbook: validator.yml
- import_playbook: netstat.yml
- import_playbook: explorer.yml
- import_playbook: moc.yml
