---
- hosts: all
  user: ubuntu
  become: True
#  user: root
  roles:
    - preconf
  tags: preconf

#- hosts: all
#  user: root
#  roles:
#    - iptables
#  tags: iptables


- hosts: bootnode
  vars:
    username: "bootnode"
    users:
      - name: "bootnode"
    home: "/home/bootnode"
#    logsprefix: "/home/bootnode/logs"
#    logentries_user_key: "0665901a-e843-41c5-82c1-2cc4b39f0b21"
  roles:
    - usermanager
#    - logentries
    - nodejs
    - bootnode
    - nginx
  tags:
    - bootnode

- hosts: mining
  vars:
    username: "mining"
    users:
      - name: "mining"
    home: "/home/mining"
#    logsprefix: "/home/mining/logs"
#    logentries_user_key: "0665901a-e843-41c5-82c1-2cc4b39f0b21"
  roles:
    - usermanager
#    - logentries
    - nodejs
    - mining
  tags:
    - mining
