---
- name: Debug spec_json
  var: spec_json

- name: Copy spec.json to remote machine
  copy: src={{ spec_json }} dest={{ home }}/ mode=0644 group={{ username }} owner={{ username }}
  when: spec_json != ""

- name: Download spec.json
  get_url: url={{ item }} dest={{ home }}/ mode=0644 group={{ username }} owner={{ username }}
  with_items:
    - "https://raw.githubusercontent.com/{{ MAIN_REPO_FETCH }}/poa-chain-spec/{{ GENESIS_BRANCH }}/spec.json"
    - "https://raw.githubusercontent.com/{{ MAIN_REPO_FETCH }}/poa-chain-spec/{{ GENESIS_BRANCH }}/bootnodes.txt"
  when: spec_json == ""