---
- name: Copy spec.json and bootnodes.txt to remote machine
  delegate_to: "{{ spec_source }}"
  synchronize: src={{ item }} dest={{ home }}/ mode=pull
  when: spec_json != ""
  with_items:
    - "{{ spec_json }}"
    - "{{ bootnodes_txt }}"
    
- name: Set proper rights to files
  file:
    mode: 0644
    group: "{{ username }}"
    owner: "{{ username }}"
    path: "{{ home }}/{{ item }}"
  when: spec_json != ""
  with_items:
    - "{{ spec_json }}"
    - "{{ bootnodes_txt }}"

- name: Download spec.json and bootnodes.txt
  get_url: url={{ item }} dest={{ home }}/ mode=0644 group={{ username }} owner={{ username }}
  with_items:
    - "https://raw.githubusercontent.com/{{ MAIN_REPO_FETCH }}/poa-chain-spec/{{ GENESIS_BRANCH }}/spec.json"
    - "https://raw.githubusercontent.com/{{ MAIN_REPO_FETCH }}/poa-chain-spec/{{ GENESIS_BRANCH }}/bootnodes.txt"
  when: spec_json == ""