---
- name: Create directory parity_data/keys/OraclesPoA
  file:
    path: "{{ home }}/parity_data/keys/OraclesPoA"
    state: directory
    mode: 0700
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Create logs directories
  file:
    path: "/{{ home }}/logs/old"
    state: directory
    mode: 0755
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Download spec.json
  get_url: url={{ item }} dest={{ home }}/ mode=0644
  with_items:
    - "https://raw.githubusercontent.com/{{ MAIN_REPO_FETCH }}/oracles-scripts/sokol/spec.json"
    - "https://raw.githubusercontent.com/{{ MAIN_REPO_FETCH }}/deployment-azure/{{ TEMPLATES_BRANCH }}/nodes/bootnodes.txt"
    - "https://raw.githubusercontent.com/{{ MAIN_REPO_FETCH }}/deployment-azure/{{ TEMPLATES_BRANCH }}/nodes/netstats-server/node.toml"


- name: Change nat in node.toml
  lineinfile: 
    path: "{{ home }}/node.toml"
    insertafter: '^\[network\]'
    line: nat="extip:{{ ansible_host }}"
    state: present

- name: Change reserved_peers in node.toml
  lineinfile: 
    path: "{{ home }}/node.toml"
    insertafter: '^\[network\]'
    line: reserved_peers="{{ home }}/bootnodes.txt"
    state: present

- name: Add log file in node.toml
  blockinfile: 
    path: "{{ home }}/node.toml"
    block: |
      [misc]
      log_file = "{{ home }}/logs/parity.log"

- git: repo=https://github.com/{{ MAIN_REPO_FETCH }}/eth-netstats dest={{ home }}/eth-netstats

- file: path={{ home }} owner={{ username }} group={{ username }} recurse=yes

- name: install npm netstats
  shell: "cd /home/{{ username }}/eth-netstats; /usr/bin/npm install"
  become: true
  become_user: "{{ username }}"
  notify:
    - restart oracles-dashboard

- name: install npm grunt-cli
  shell: "cd /home/{{ username }}/eth-netstats; /usr/bin/npm install -g grunt-cli"

- name: run grunt process
  shell: "cd /home/{{ username }}/eth-netstats; grunt"
  become: true
  become_user: "{{ username }}"

- name: Config ws_secret.json file
  shell: "echo '[\"{{ NETSTATS_SECRET }}\"]' > /home/{{ username }}/eth-netstats/ws_secret.json"
  notify:
    - restart oracles-dashboard

- name: Install oracles-dashboard service
  template: src=oracles-dashboard.j2 dest=/etc/systemd/system/oracles-dashboard.service owner=root group=root mode=0755
  notify:
    - restart oracles-dashboard

- name: Ensure oracles-dashboard is running and enabled to start at boot
  service: name=oracles-dashboard state=started enabled=yes
