---

user: ubuntu

allow_blockscout_ssh: true
allow_blockscout_p2p: true
allow_blockscout_http: false

username: "blockscout"
users:
- name: "{{ username }}"
home: "/home/{{ username }}"

MAIN_REPO_FETCH: "poanetwork"
MOC_ADDRESS: "0xdd0bb0e2a1594240fed0c2f2c17c1e9ab4f87126"

reboot_after_completion: false
install_debug_tools: "no"
install_firewall: false

blockscout_version: "44e4f17d14"
db_user: "blockscout"
PROXY_PORT: "4000"