---
- name: Create directory parity_data/keys/OraclesPoA
  file:
    path: "{{ home }}/parity_data/keys/OraclesPoA"
    state: directory
    mode: 0700
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Create logs directories
  file:
    path: "/{{ home }}/logs/old"
    state: directory
    mode: 0755
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Install oracles-pm2 service
  template: src=oracles-pm2.j2 dest=/etc/systemd/system/oracles-pm2.service owner=root group=root mode=0755
  notify:
    - restart oracles-pm2

- name: Install npm pm2
  npm: name="pm2" global="yes"
  notify:
    - restart oracles-pm2

- name: Ensure oracles-pm2 is running and enabled to start at boot
  service: name=oracles-pm2 state=started enabled=yes
