---
- name: Create directory parity_data/keys/NetworkName
  file:
    path: "{{ home }}/parity_data/keys/{{ GENESIS_NETWORK_NAME }}"
    state: directory
    mode: 0700
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Create logs directories
  file:
    path: "/{{ home }}/logs/old"
    state: directory
    mode: 0755
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Download spec.json
  get_url: url={{ item }} dest={{ home }}/ mode=0644
  with_items:
    - "https://raw.githubusercontent.com/{{ MAIN_REPO_FETCH }}/poa-chain-spec/{{ GENESIS_BRANCH }}/spec.json"
    - "https://raw.githubusercontent.com/{{ MAIN_REPO_FETCH }}/deployment-azure/{{ TEMPLATES_BRANCH }}/nodes/bootnodes.txt"
    - "https://raw.githubusercontent.com/{{ MAIN_REPO_FETCH }}/deployment-azure/{{ TEMPLATES_BRANCH }}/nodes/owner/node.toml"

- name: Change nat in node.toml
  lineinfile:
    path: "{{ home }}/node.toml"
    insertafter: '^\[network\]'
    line: nat="extip:{{ ansible_host }}"
    state: present

- name: Change reserved_peers in node.toml
  lineinfile:
    path: "{{ home }}/node.toml"
    insertafter: '^\[network\]'
    line: reserved_peers="{{ home }}/bootnodes.txt"
    state: present

- name: Add log file in node.toml
  blockinfile:
    path: "{{ home }}/node.toml"
    block: |
      [misc]
      log_file = "{{ home }}/logs/parity.log"
      [account]
      password = ["{{ NODE_PWD }}"]
      #unlock = ["{{ MOC_ADDRESS }}"]
      [mining]
      force_sealing = true
      engine_signer = "{{ MOC_ADDRESS }}"
      gas_floor_target = "{{ BLK_GAS_LIMIT }}"
      reseal_on_txs = "none"

- name: Install {{ NODE_PWD }} file
  template: src=node_pwd.j2 dest={{ home }}/{{ NODE_PWD }} owner={{ username }} group={{ username }} mode=0600

- name: Config MOC_KEYFILE file
  shell: "echo '{{ MOC_KEYFILE }}' > {{ home }}/parity_data/keys/{{ GENESIS_NETWORK_NAME }}/{{ username }}.key"

- git: repo=https://github.com/{{ MAIN_REPO_FETCH }}/poa-scripts-owner dest={{ home }}/poa-scripts-owner version={{ SCRIPTS_MOC_BRANCH }}

- file: path={{ home }}/poa-scripts-owner owner={{ username }} group={{ username }} recurse=yes

- name: install npm initial_keys_script
  shell: "cd {{ home }}/poa-scripts-owner; /usr/bin/npm install"
  become: true
  become_user: "{{ username }}"

- name: install npm generateInitialKey
  shell: "cd {{ home }}/poa-scripts-owner/generateInitialKey; /usr/bin/npm install"
  become: true
  become_user: "{{ username }}"

- name: install npm distributeTokens
  shell: "cd {{ home }}/poa-scripts-owner/distributeTokens; /usr/bin/npm install"
  become: true
  become_user: "{{ username }}"
