---
- name: Create directory parity_data/keys/NetworkName
  file:
    path: "{{ home }}/parity_data/keys/{{ GENESIS_NETWORK_NAME }}"
    state: directory
    mode: 0700
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Create logs directories
  file:
    path: "/{{ home }}/logs/old"
    state: directory
    mode: 0755
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Download spec.json
  get_url: url={{ item }} dest={{ home }}/ mode=0644
  with_items:
    - "https://raw.githubusercontent.com/{{ MAIN_REPO_FETCH }}/poa-chain-spec/{{ GENESIS_BRANCH }}/spec.json"
    - "https://raw.githubusercontent.com/{{ MAIN_REPO_FETCH }}/poa-chain-spec/{{ GENESIS_BRANCH }}/bootnodes.txt"
    - "https://raw.githubusercontent.com/{{ MAIN_REPO_FETCH }}/deployment-azure/{{ TEMPLATES_BRANCH }}/nodes/mining-node/node.toml"

- name: Change nat in node.toml
  lineinfile:
    path: "{{ home }}/node.toml"
    insertafter: '^\[network\]'
    line: nat="extip:{{ ansible_host }}"
    state: present

- name: Change reserved_peers in node.toml
  lineinfile:
    path: "{{ home }}/node.toml"
    insertafter: '^\[network\]'
    line: reserved_peers="{{ home }}/bootnodes.txt"
    state: present

- name: Add log file in node.toml
  blockinfile:
    path: "{{ home }}/node.toml"
    block: |
      [misc]
      log_file = "{{ home }}/logs/parity.log"
      [account]
      password = ["{{ NODE_PWD }}"]
      unlock = ["{{ MINING_ADDRESS }}"]
      [mining]
      force_sealing = true
      engine_signer = "{{ MINING_ADDRESS }}"
      gas_floor_target = "{{ BLK_GAS_LIMIT }}"
      reseal_on_txs = "none"

- name: Install {{ NODE_PWD }} file
  template: src=node_pwd.j2 dest={{ home }}/{{ NODE_PWD }} owner={{ username }} group={{ username }} mode=0600

- name: Config MINING_KEYFILE file
  shell: "echo '{{ MINING_KEYFILE }}' > {{ home }}/parity_data/keys/{{ GENESIS_NETWORK_NAME }}/validator.key.{{ MINING_ADDRESS }}"

- git: repo=https://github.com/{{ MAIN_REPO_FETCH }}/poa-scripts-validator dest={{ home }}/poa-scripts-validator version={{ SCRIPTS_VALIDATOR_BRANCH }}

- file: src="{{ home }}/node.toml" dest="{{ home }}/poa-scripts-validator/node.toml" owner="{{ username }}" group="{{ username }}" state=link

- file: path={{ home }}/poa-scripts-validator owner={{ username }} group={{ username }} recurse=yes

- name: install npm transferRewardToPayoutKey
  shell: "cd {{ home }}/poa-scripts-validator/transferRewardToPayoutKey; /usr/bin/npm install"
  become: true
  become_user: "{{ username }}"
  notify:
    - restart poa-netstats

- name: Install Payout task.
  template: src=transferRewardToPayoutKey.j2 dest=/etc/cron.hourly/transferRewardToPayoutKey owner=root group=root mode=0755
