---

- name: Create node.toml
  template: src={{ item }}.j2 dest={{ home }}/node.toml owner=root group=root mode=0644
  with_items:
   - node.toml
   
- name: Setup ufw firewall
  import_tasks: ufw.yml
  when: not ansible_bios_version | search("amazon")

#- file: path={{ home }} owner={{ username }} group={{ username }} recurse=yes
