---

- name: Create node.toml
  template: src=node.toml.j2 dest={{ home }}/node.toml owner={{ username }} group={{ username }} mode=0644
   
- name: Setup ufw firewall
  import_tasks: ufw.yml
  when: not ansible_bios_version is search("amazon")
  
- name: restart machine after setup
  shell: shutdown -r 1
  when: reboot_after_completion == true

#- file: path={{ home }} owner={{ username }} group={{ username }} recurse=yes
